### ISSUE TITLE
Change the "Zone" field name in the Editor page

### ISSUE THREAD

**Issue by agaidinstituteadmin** [CafIncubator/Midden#111]
The term "Zone" might be confusing for people working with cloud computing or from the Ag domain where Zone has another meaning.

**Comment by bryanrcarlson** [comment]
How about "Layer"? I see this in data science literature as well; "Bronze Layer" / "Raw Layer", etc.

"Table" tends to be used too, but I don't think that has too many connotations to databases.

**Comment by agaidinstituteadmin** [comment]
I will check the use of layer because for our researchers it will have a different meaning. Also, in CS layer is used for hardware, software, the layer in the development process. I still think something in the line of "Stage", "Status" will be more simple
