### ISSUE TITLE
Error when using a "\" in the item name attribute 

### ISSUE THREAD

**Issue by riemino** [CafIncubator/Midden#44]
An error occurs when loading the catalog.json into the web Catalog when using a "\" in the item name attribute in a midden file.  Looks like the editor can create it, but when I tried to see the item in the catalog, I was getting an error (not able to open the item).

**Comment by bryanrcarlson** [comment]
@riemino ; I'm unable to reproduce this error. Is this when using the editor or when manually editing the catalog.json file?

Adding a "\\" in the Name, Project, and Description input areas with the editor seems to escape it correctly when downloading the .midden file. Loading that file into the editor properly displays it as well.

If you open the catalog.json file, or any .midden file in a text editor the "\\" character should be escaped (e.g. "\\\\"). If it is not, then the editor will indeed fail (silently) on load. 

(adding an error message would be nice, but may need to wait until a UX polishing release)
