### ISSUE TITLE
Include version in all web app pages

### ISSUE THREAD

**Issue by riemino** [CafIncubator/Midden#55]
The Midden version is currently only seen in the Editor.  Either including it in the header or the footer should work so that it can be visible in Insights, Catalog, and homepage.

**Comment by bryanrcarlson** [comment]
Great idea! 

Footer? 
![image](https://user-images.githubusercontent.com/12533203/134361903-981fc36f-503f-46fc-bb86-4ba6f3a8a41c.png)

Or header?
![image](https://user-images.githubusercontent.com/12533203/134362095-974f56bb-0392-4fda-9480-8c2d8059d539.png)

Or other?

**Comment by bryanrcarlson** [comment]
Looking at the code, the version shown in the Editor is actually the schemaVersion (of the .midden files) from app-config. Eventually this will diverge from the version of the web tools. Showing both will likely be confusing.

I think displaying the schema version was a mistake. The editor should be compatible with all previous schema version, so there's no real reason to specify the current version. Also, the version of the schema is included in each .midden file and the catalog.json file. 

I think the version that @riemino proposed should be the assembly version of the [Caf.Midden.Wasm](https://github.com/CafIncubator/Midden/tree/main/Caf.Midden.Wasm) project (which includes the web tools; home, insights, catalog, editor). I believe this can be determined at runtime using ```Assembly```. 

We'll also need to be more diligent with updating the assembly version if we do this. Which we should anyway. (probably look into the msbump package or other automated ways to aid in this)
